name: Sync Fork

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: Loyalsoldier
          base: hidden
          head: hidden
